spring.application.name=login-service
spring.datasource.url=jdbc:mysql://localhost:3306/db_nuestra_empresa
spring.datasource.username=root
spring.datasource.password=juanmy23
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9095
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
spring.config.import=optional:configserver:http://localhost:8888